---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: fe-demo-2
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        repoURL: https://github.com/minhnd410/demo-argocd.git
        targetRevision: HEAD
        path: environments/staging/fe-demo-2
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - Validate=true
            - CreateNamespace=false
            - PrunePropagationPolicy=foreground
            - PruneLast=true